#
# Module manifest for module 'Format-AsciiArtTable'
# Generated by: Peter.Vandivier
# Generated on: 2023-04-28
#
@{
    ModuleVersion = '0.0.1'
    GUID          = 'ddecd499-e8f5-43ad-94d1-47f140e9d7da'
    Author        = 'Peter.Vandivier'
    Copyright     = '(c) Peter.Vandivier. All rights reserved.'
    Description   = 'Creates an ASCII art table from a PS Object. Requires `jq`'
    RootModule    = 'Format-AsciiArtTable.psm1'
    FunctionsToExport = @(
        'Format-AsciiArtTable'
    )
}
